name: flutter_jifen
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dio: ^3.0.8
  json_annotation: ^3.0.0
  simple_rc4: ^0.1.6
  retrofit: ^1.3.4
  logger: any
  provider: ^4.3.2
  # 官方toast库
  fluttertoast: ^4.0.0
  # 时间格式化
  intl: ^0.16.1
  # placeHolder透明图片
  transparent_image: ^1.0.0
  # 提供类似Pair的数据结构
  tuple: ^1.0.3
  # 时间选择器
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/huanlirui/flutter-cupertino-date-picker
      ref: master
  # 加载网页
  # webview_flutter: ^0.3.21
  # 滑动到指定位置的ListView 修复了数据
  scrollable_positioned_list:
    git:
      url: git://github.com/keep2iron/flutter.widgets.git
      path: packages/scrollable_positioned_list
  # scrollable_positioned_list: ^0.1.6
  # 城市选择器 代码质量一般 后面可能会自己写一个
  city_pickers: ^0.1.30
  # progress dialog
  flutter_progress_dialog: ^0.1.0
  # rxdart
  rxdart: ^0.24.1
  # # bugly日志收集
  # bugly_crash:
  #   git:
  #     url: git://github.com/keep2iron/Bugly-Flutter-Plugin.git
  # 图片缓存框架
  cached_network_image: ^2.2.0+1
  # 侧滑框架
  flutter_slidable: ^0.5.4
  # share_preference
  shared_preferences: ^0.5.7+3
  # widget 可见性组件
  visibility_detector: ^0.1.5
  # 嵌入式HTML组件
  flutter_html: ^1.0.0
  # 图片放大查看器
  photo_view: ^0.9.2
  # 网格瀑布流
  #  flutter_staggered_grid_view: ^0.3.2
  flutter_staggered_grid_view:
    git:
      url: https://github.com/BertrandBev/flutter_staggered_grid_view.git
  # 吸顶
  flutter_sticky_header: ^0.4.2
  # 视频播放器
  video_player: ^0.10.11+2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 上拉刷新，下拉加载
  pull_to_refresh: ^1.6.0
  flutter_easyrefresh: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.4.1
  retrofit_generator: ^1.3.1+9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
